### ISSUE TITLE
Urbanisme Evolutions

### ISSUE THREAD

**Issue by tdipisa** [sigrennesmetropole/geor_urbanisme_mapstore#42]
By using Urbanisme, we identified evolutions to be made so that the behaviour of this plugin
is copied from Cadastrapp. Indeed, these two plugins are used by the same people:

- The loading of the app:urbanisme_parcelle layer, which is used to query the data,
must be done without it appearing in the list of layers,
- When a layer group or a layer is selected in the layer list, the NRU and ADS buttons
do not work: align with the behaviour of cadastrapp.

**Comment by offtherailz** [comment]
Release rc8 with this fixes ready for download and test
https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v1.0.0-rc8

**Comment by tdipisa** [comment]
@ElenaGallo you can proceed with functional tests on [geosolutions DEV](https://georchestra.geo-solutions.it/header/)

**Comment by ElenaGallo** [comment]
Hi @alexander-fedorenko @tdipisa , I noticed two small issues:

1_ The sidebar moves when it activates identify while the Urbanisme app is active. See the gif below:

![2](https://user-images.githubusercontent.com/56537133/155124753-9c71f6d9-c8da-4cf0-9c95-364dbfed8244.gif)

2_ The Identifica marker remains visible even after opening the Urbanisme app.See the gif below:

![3](https://user-images.githubusercontent.com/56537133/155124770-7cc3fcc1-346b-40a8-9644-4b3fcf4d1a06.gif)

**Comment by tdipisa** [comment]
@alexander-fedorenko we should fix both

>1_ The sidebar moves when it activates identify while the Urbanisme app is active. See the gif below:

Both plugins (Urbanisme and Identify) take control of the map click event, therefore they cannot be active together at the same time. The Identify is automatically deactivated when the Urbanisme tool is opened but there should be a way to disable one of the Urbanisme buttons that interact with the map when the Identify is activated and vice versa (without closing the Urbanisme at all if possible). The sidebar should not move to the left in any case if there is no information to show.

>2_ The Identifica marker remains visible even after opening the Urbanisme app.See the gif below:

We should try to fix it as well anyway.

**Comment by offtherailz** [comment]
Tested the PR locally worked (after a small fix). So I merged and installed. But on the server it doesn't seems work. 
Maybe some misalignement or race condition. Please @alexander-fedorenko fix this and the test that was failing. 
I added github actions (need to test with your PR) to provide previous checks and avoid future problems.

https://user-images.githubusercontent.com/1279510/155977327-f533a376-bda8-40af-803f-e885a4bc4cea.mp4

**Comment by alexander-fedorenko** [comment]
@offtherailz I've created first PR before PR branch was on the revision with checks.yml available. I've closed that one, rebased branch on top of master and tried to recreate PR to check that tests were triggered but for some reason they weren't.
Tests issue should be solved. I was not able to reproduce issue on local installation too (I've tested in geOrchestra too), though I've tracked the possible issue directly on https://georchestra.geo-solutions.it/mapstore/ and applied test fix.

**Comment by offtherailz** [comment]
Sure, no problems. I noticed that doing automatic test is more useful to identify possible issues or regression
I also fixed checks.yml now. 
So you can continue working on it.

**Comment by jusabatier** [comment]
I just tested [v1.0.0-rc8](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v1.0.0-rc8) and it doesn't work on our platform.

Nothing happen when clicking on a plot...

Here is our plugin conf : 

```
{
  "cfg": {
    "helpUrl": "http://docs.georchestra.org/addon_urbanisme/",
    "cadastrappUrl": "/cadastrapp/services",
    "urbanismeappUrl": "/servitudes",
    "layer": "pci:geo_parcelle",
    "idParcelleKey": "geo_parcelle"
  },
  "override": {}
}
```

**Comment by offtherailz** [comment]
could you try [rc9 pre-release draft](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/untagged-c917bbd402328d0dcd7e) that we are actially testing?

**Comment by jusabatier** [comment]
Your link is broken

**Comment by jusabatier** [comment]
Just tested with Artefact generated from master (github actions) but it still not work

**Comment by jusabatier** [comment]
Notice that we use mapstore configured with EPSG:2154 on our platform, don't know if it can affect this plugin

**Comment by offtherailz** [comment]
> Your link is broken
Probably draft PR are not accessible externally. I published it [here](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v1.0.0-rc9) now. 

> Notice that we use mapstore configured with EPSG:2154 on our platform, don't know if it can affect this plugin

We tested `EPSG:2154` in a local  env and it seems to work. 

mmm.. you said : 

> Nothing happen when clicking on a plot...

Do you see any error or request in the developers tools network tab ?

**Comment by jusabatier** [comment]
I have no error in console, but 2 request are sent : 

First request : 

> https://geoportail.lepuyenvelay.fr/geoserver/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&exceptions=application%2Fjson&id=__URBANISME_RASTER_LAYER__&layers=pci:geo_parcelle&query_layers=pci:geo_parcelle&x=51&y=51&height=101&width=101&srs=EPSG:2154&bbox=769084.8502007792,6438111.0366231445,770049.8676828794,6439076.054105245&feature_count=10&info_format=application%2Fjson&ENV=

Reponse : 

> {"type":"FeatureCollection","features":[],"totalFeatures":"unknown","numberReturned":0,"timeStamp":"2022-03-04T12:28:39.846Z","crs":null}

Second request : 

> https://geoportail.lepuyenvelay.fr/geoserver/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&exceptions=application%2Fjson&id=__URBANISME_RASTER_LAYER__&layers=pci:geo_parcelle&query_layers=pci:geo_parcelle&x=51&y=51&height=101&width=101&srs=EPSG:2154&bbox=769084.8502007792,6438111.0366231445,770049.8676828794,6439076.054105245&feature_count=10&info_format=text%2Fhtml&ENV=

Reponse : 

```
<html>
  <head>
    <title>Geoserver GetFeatureInfo output</title>
  </head>
  <style type="text/css">
	table.featureInfo, table.featureInfo td, table.featureInfo th {
		border:1px solid #ddd;
		border-collapse:collapse;
		margin:0;
		padding:0;
		font-size: 90%;
		padding:.2em .1em;
	}
	table.featureInfo th {
	    padding:.2em .2em;
		font-weight:bold;
		background:#eee;
	}
	table.featureInfo td{
		background:#fff;
	}
	table.featureInfo tr.odd td{
		background:#eee;
	}
	table.featureInfo caption{
		text-align:left;
		font-size:100%;
		font-weight:bold;
		padding:.2em .2em;
	}
  </style>
  <body>
  
  </body>
</html>
```

After that requests, nothing happen.

It look like it can't retrieve the feature.

I compared with a working equivalent request and the only difference seems to be the boundingbox parameter.

**Comment by offtherailz** [comment]
Thank you for this information. We will try to replicate find out the reason of this.

**Comment by offtherailz** [comment]
@jusabatier can you try this version? 
[Urbanisme.zip](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/files/8260413/Urbanisme.zip)

**Comment by jusabatier** [comment]
I can confirm you that the last merged PR (https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/pull/49) solve the issue.

**Comment by offtherailz** [comment]
Thank you. I updated the latest release zip file with these fixes

**Comment by catmorales** [comment]
@tdipisa , I just deployed the  [v1.0.0-rc9 ](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/releases/tag/v1.0.0-rc9)on portail-test﻿ and the required improvements seems to be ok.
Thank you.

**Comment by tdipisa** [comment]
Thank you too @catmorales I'm going to close then.
